Allowed devstack not fail if couldn't stop smb service
Support of nfs and samba services is present for
single-tenant drivers.
By default used multitenant generic driver, that does not use
host's services, so if fail occures with stopping of this service
just go further.

Change-Id: I45e0ffb24f213c7fc68c583951af792d9bfccf39

diff --git a/contrib/devstack/lib/manila b/contrib/devstack/lib/manila
--- a/contrib/devstack/lib/manila
+++ b/contrib/devstack/lib/manila
@@ -404,7 +404,7 @@ function start_manila {
         if is_fedora; then
             samba_daemon_name=smb
         fi
-        stop_service $samba_daemon_name
+        stop_service $samba_daemon_name || echo "Couldn't stop '$samba_daemon_name' service"
     fi
 
     screen_it m-api "cd $MANILA_DIR && $MANILA_BIN_DIR/manila-api --config-file $MANILA_CONF"
